import { shallowMount, flushPromises } from '@vue/test-utils'
import { ref } from 'vue'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import PsychMaster from './PsychMaster.vue'
import ChatRoom from '../components/ChatRoom.vue'
import ConversationSidebar from '../components/ConversationSidebar.vue'
import MemoryDigestCard from '../components/MemoryDigestCard.vue'
import * as api from '../api'
const authMocks = vi.hoisted(() => ({ logout: vi.fn(), push: vi.fn() }))

vi.mock('vue-router', () => ({ useRouter: () => ({ push: authMocks.push }) }))
vi.mock('@unhead/vue', () => ({ useHead: vi.fn() }))
vi.mock('../stores/auth', () => ({ useAuth: () => ({ me: ref({ username: 'tester' }), isAdmin: ref(false), logout: authMocks.logout, clearAuth: vi.fn(), setAuthNotice: vi.fn() }) }))
vi.mock('../api', () => ({ chatWithPsychApp: vi.fn(), changeMyPassword: vi.fn(), createConversation: vi.fn(), deleteConversation: vi.fn(), getConversation: vi.fn(), getConversations: vi.fn() }))

const detail = id => ({ id, messages: [{ id: 1, role: 'assistant', content: id, createdAt: '2026-09-17T00:00:00Z' }] })
const deferred = () => {
  let resolve, reject
  const promise = new Promise((res, rej) => { resolve = res; reject = rej })
  return { promise, resolve, reject }
}
const memory = label => ({ updatedAt: label, digestedCount: 1, messageCount: 4, maxMessages: 20, digestChars: 10 })
const finishTurn = (wrapper, payload = { type: 'done' }) => {
  wrapper.getComponent(ChatRoom).vm.$emit('send-message', '你好')
  const stream = api.chatWithPsychApp.mock.results.at(-1).value
  stream.onmessage({ data: JSON.stringify(payload) })
}
describe('conversation and stream state', () => {
  beforeEach(() => {
    vi.resetAllMocks()
    authMocks.logout.mockReset()
    localStorage.clear()
    api.getConversations.mockResolvedValue([{ id: 'first', title: 'first' }])
    api.getConversation.mockImplementation(async id => detail(id))
    api.chatWithPsychApp.mockImplementation(() => ({ close: vi.fn(), onmessage: null, onerror: null }))
  })
  afterEach(() => {
    vi.useRealTimers()
    vi.restoreAllMocks()
  })
  it.each(['response', 'failure'])('ignores an older list %s after a newer list succeeds', async outcome => {
    const wrapper = shallowMount(PsychMaster)
    await flushPromises()
    const older = deferred(), newer = deferred()
    api.getConversations.mockReturnValueOnce(older.promise).mockReturnValueOnce(newer.promise)
    finishTurn(wrapper, { type: 'error', phase: 'partial', content: '旧轮次提示' })
    finishTurn(wrapper, { type: 'error', phase: 'partial', content: '新轮次提示' })
    newer.resolve([{ id: 'first', title: '最新标题' }])
    await flushPromises()
    if (outcome === 'response') older.resolve([{ id: 'stale', title: '过期列表' }])
    else older.reject(new Error('old request failed'))
    await flushPromises()
    const sidebar = wrapper.getComponent(ConversationSidebar)
    expect(sidebar.props('conversations')).toEqual([{ id: 'first', title: '最新标题' }])
    expect(sidebar.props('error')).toBe('新轮次提示')
    expect(sidebar.props('loading')).toBe(false)
    wrapper.unmount()
  })
  it('loads each selection once and lets a return to A supersede pending B', async () => {
    const wrapper = shallowMount(PsychMaster)
    await flushPromises()
    const pendingB = deferred()
    api.getConversation.mockClear()
    api.getConversation.mockReturnValueOnce(pendingB.promise)
    const sidebar = wrapper.getComponent(ConversationSidebar)
    sidebar.vm.$emit('select', 'b')
    sidebar.vm.$emit('select', 'first')
    await flushPromises()
    pendingB.resolve(detail('b'))
    await flushPromises()
    expect(api.getConversation.mock.calls).toEqual([['b'], ['first']])
    expect(sidebar.props('activeId')).toBe('first')
    expect(wrapper.getComponent(ChatRoom).props('messages')[0].content).toBe('first')
    expect(wrapper.getComponent(ChatRoom).props('inputDisabled')).toBe(false)
    wrapper.unmount()
  })
  it('ignores an old memory response after A to B to A and cancels its settle chain', async () => {
    vi.useFakeTimers()
    const wrapper = shallowMount(PsychMaster)
    await flushPromises()
    const oldMemory = deferred()
    api.getConversation.mockReturnValueOnce(oldMemory.promise)
    finishTurn(wrapper)
    await flushPromises()
    const sidebar = wrapper.getComponent(ConversationSidebar)
    sidebar.vm.$emit('select', 'b')
    await flushPromises()
    api.getConversation.mockResolvedValueOnce({ ...detail('first'), memory: memory('new A') })
    sidebar.vm.$emit('select', 'first')
    await flushPromises()
    const calls = api.getConversation.mock.calls.length
    oldMemory.resolve({ ...detail('first'), memory: memory('old A') })
    await flushPromises()
    await vi.advanceTimersByTimeAsync(15000)
    expect(wrapper.getComponent(MemoryDigestCard).props('memory')).toEqual(memory('new A'))
    expect(api.getConversation).toHaveBeenCalledTimes(calls)
    expect(vi.getTimerCount()).toBe(0)
    wrapper.unmount()
  })
  it('discards pending detail, memory and list responses when deleting a conversation', async () => {
    vi.useFakeTimers()
    vi.spyOn(window, 'confirm').mockReturnValue(true)
    const wrapper = shallowMount(PsychMaster)
    await flushPromises()
    const oldMemory = deferred(), oldList = deferred(), oldDetail = deferred(), deletion = deferred()
    api.getConversation.mockReturnValueOnce(oldMemory.promise).mockReturnValueOnce(oldDetail.promise)
    api.getConversations.mockReturnValueOnce(oldList.promise).mockResolvedValueOnce([{ id: 'remaining', title: '保留' }])
    api.deleteConversation.mockReturnValueOnce(deletion.promise)
    finishTurn(wrapper)
    const sidebar = wrapper.getComponent(ConversationSidebar)
    sidebar.vm.$emit('select', 'pending')
    sidebar.vm.$emit('delete', { id: 'first', title: 'first' })
    deletion.resolve()
    await flushPromises()
    oldDetail.resolve(detail('pending'))
    oldMemory.resolve({ ...detail('first'), memory: memory('deleted') })
    oldList.resolve([{ id: 'first', title: '已删除' }])
    await flushPromises()
    const calls = api.getConversation.mock.calls.length
    await vi.advanceTimersByTimeAsync(15000)
    expect(sidebar.props('conversations')).toEqual([{ id: 'remaining', title: '保留' }])
    expect(sidebar.props('activeId')).toBe('remaining')
    expect(wrapper.getComponent(ChatRoom).props('messages')[0].content).toBe('remaining')
    expect(wrapper.getComponent(MemoryDigestCard).props('memory')).toBeNull()
    expect(api.getConversation).toHaveBeenCalledTimes(calls)
    expect(vi.getTimerCount()).toBe(0)
    wrapper.unmount()
  })
  it('ends the settle chain when unmounted while a refresh is in flight', async () => {
    vi.useFakeTimers()
    api.getConversation.mockImplementation(async id => ({ ...detail(id), memory: memory('unchanged') }))
    const wrapper = shallowMount(PsychMaster)
    await flushPromises()
    finishTurn(wrapper)
    await flushPromises()
    const pending = deferred()
    api.getConversation.mockReturnValueOnce(pending.promise)
    await vi.advanceTimersByTimeAsync(1200)
    const calls = api.getConversation.mock.calls.length
    wrapper.unmount()
    pending.resolve({ ...detail('first'), memory: memory('unchanged') })
    await flushPromises()
    await vi.advanceTimersByTimeAsync(15000)
    expect(api.getConversation).toHaveBeenCalledTimes(calls)
    expect(vi.getTimerCount()).toBe(0)
  })
  it('clears a waiting settle timer immediately on unmount', async () => {
    vi.useFakeTimers()
    const wrapper = shallowMount(PsychMaster)
    await flushPromises()
    finishTurn(wrapper)
    await flushPromises()
    expect(vi.getTimerCount()).toBe(1)
    const calls = api.getConversation.mock.calls.length
    wrapper.unmount()
    expect(vi.getTimerCount()).toBe(0)
    await vi.advanceTimersByTimeAsync(15000)
    expect(api.getConversation).toHaveBeenCalledTimes(calls)
  })
  it('does not continue initialization after unmount', async () => {
    const pending = deferred()
    api.getConversations.mockReturnValueOnce(pending.promise)
    const wrapper = shallowMount(PsychMaster)
    wrapper.unmount()
    pending.resolve([{ id: 'late', title: 'late' }])
    await flushPromises()
    expect(api.getConversation).not.toHaveBeenCalled()
    expect(api.createConversation).not.toHaveBeenCalled()
  })
  it('invalidates pending reads and timers when logout starts, including after logout fails', async () => {
    vi.useFakeTimers()
    const wrapper = shallowMount(PsychMaster)
    await flushPromises()
    const pendingList = deferred(), pendingMemory = deferred()
    api.getConversations.mockReturnValueOnce(pendingList.promise)
    api.getConversation.mockReturnValueOnce(pendingMemory.promise)
    authMocks.logout.mockRejectedValueOnce(new Error('network'))
    finishTurn(wrapper)
    await wrapper.get('.logout-button').trigger('click')
    await flushPromises()
    pendingList.reject(new Error('stale failure'))
    pendingMemory.resolve({ ...detail('first'), memory: memory('stale') })
    await flushPromises()
    const calls = api.getConversation.mock.calls.length
    await vi.advanceTimersByTimeAsync(15000)
    expect(wrapper.getComponent(ConversationSidebar).props('error')).toContain('尚未确认退出')
    expect(wrapper.getComponent(MemoryDigestCard).props('memory')).toBeNull()
    expect(api.getConversation).toHaveBeenCalledTimes(calls)
    expect(vi.getTimerCount()).toBe(0)
    wrapper.unmount()
  })
  it('shows unconfirmed logout and stays on the page when the request fails', async () => {
    authMocks.logout.mockRejectedValue(new Error('network'))
    const wrapper = shallowMount(PsychMaster)
    await flushPromises()
    await wrapper.get('.logout-button').trigger('click')
    await flushPromises()
    expect(wrapper.getComponent(ConversationSidebar).props('error')).toContain('尚未确认退出')
    expect(authMocks.push).not.toHaveBeenCalled()
    expect(wrapper.get('.logout-button').attributes('disabled')).toBeUndefined()
    wrapper.unmount()
  })
  it('ignores an older conversation response after a newer selection', async () => {
    const wrapper = shallowMount(PsychMaster)
    await flushPromises()
    const a = deferred(), b = deferred()
    api.getConversation.mockImplementation(id => id === 'a' ? a.promise : b.promise)
    const sidebar = wrapper.getComponent(ConversationSidebar)
    sidebar.vm.$emit('select', 'a')
    sidebar.vm.$emit('select', 'b')
    b.resolve(detail('b')); await flushPromises()
    a.resolve(detail('a')); await flushPromises()
    expect(sidebar.props('activeId')).toBe('b')
    expect(wrapper.getComponent(ChatRoom).props('messages')[0].content).toBe('b')
    wrapper.unmount()
  })
  it('preserves the server error after refreshing the list and does not retry a stored partial', async () => {
    const wrapper = shallowMount(PsychMaster)
    await flushPromises()
    const room = wrapper.getComponent(ChatRoom)
    room.vm.$emit('send-message', '你好')
    await flushPromises()
    const connection = api.chatWithPsychApp.mock.results[0].value
    connection.onmessage({ data: JSON.stringify({ type: 'error', phase: 'partial', content: '已保存部分回答' }) })
    await flushPromises()
    expect(wrapper.getComponent(ConversationSidebar).props('error')).toBe('已保存部分回答')
    expect(room.props('retryableTurn')).toBeNull()
    expect(connection.close).toHaveBeenCalledOnce()
    wrapper.unmount()
  })
  it('manual retry reuses the original key; stop closes the active stream', async () => {
    const wrapper = shallowMount(PsychMaster)
    await flushPromises()
    const room = wrapper.getComponent(ChatRoom)
    room.vm.$emit('send-message', '最近压力很大')
    await flushPromises()
    const first = api.chatWithPsychApp.mock.calls[0]
    api.chatWithPsychApp.mock.results[0].value.onerror(Object.assign(new Error('busy'), { status: 429 }))
    await flushPromises()
    expect(api.chatWithPsychApp).toHaveBeenCalledTimes(1)
    room.vm.$emit('retry-send'); await flushPromises()
    expect(api.chatWithPsychApp.mock.calls[1]).toEqual(first)
    const active = api.chatWithPsychApp.mock.results[1].value
    room.vm.$emit('stop-stream'); await flushPromises()
    expect(active.close).toHaveBeenCalledOnce()
    expect(room.props('connectionStatus')).toBe('disconnected')
    wrapper.unmount()
  })
})
